service: cantine-app-backend

frameworkVersion: ">=1.1.0 <2.0.0"

custom:
  defaultStage: dev
  currentStage: ${opt:stage, self:custom.defaultStage} # 'dev' is default unless overriden by --stage flag
  
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.currentStage}
  region: eu-central-1
  # environment: ${file(env.yml):${self:custom.currentStage}}

plugins:
  - serverless-plugin-typescript

functions:
  status200:
    handler: src/status.http200
    events:
      - http:
          path: status
          method: get
          cors: true

  cantines:
      handler: src/cantines.list
      events:
        - http:
            path: cantines
            method: get
            cors: true
